# Generated by Django 4.2.3 on 2023-07-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='money',
            field=models.CharField(default='asd', max_length=20),
        ),
    ]
