# Generated by Django 4.2.3 on 2023-09-03 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizecolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.color'),
        ),
        migrations.AlterField(
            model_name='productsizecolor',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.size'),
        ),
    ]
