# Generated by Django 4.2.3 on 2023-07-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_color_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='asd',
            field=models.CharField(default='asdasd', max_length=20),
        ),
    ]
