# Generated by Django 4.2.3 on 2023-08-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_product_productsizecolor_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsizecolor',
            options={'verbose_name': 'Товар - Размер - Цвет', 'verbose_name_plural': 'Товар - Размер - Цвет'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
