# Generated by Django 4.2.3 on 2023-08-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_productsizecolor_options_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizecolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='product_app.color'),
        ),
        migrations.AlterField(
            model_name='productsizecolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='productsizecolor',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='product_app.size'),
        ),
    ]
